// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8OEXh57exSA3PzDEzo01bxGpddIQZx90',
    appId: '1:906140023111:web:d76b62d677dfad2d6e7462',
    messagingSenderId: '906140023111',
    projectId: 'jakebrakelogistics-2e451',
    authDomain: 'jakebrakelogistics-2e451.firebaseapp.com',
    storageBucket: 'jakebrakelogistics-2e451.appspot.com',
    measurementId: 'G-8P4PXP31M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx99yY0kt3Qrx523cLcN3scnj0eJmI1W4',
    appId: '1:906140023111:android:4991d5e65bbe34c46e7462',
    messagingSenderId: '906140023111',
    projectId: 'jakebrakelogistics-2e451',
    storageBucket: 'jakebrakelogistics-2e451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrg8kXQG4mmVOi-plWyRy21_izDh7hyWE',
    appId: '1:906140023111:ios:cd77f1df6967e4726e7462',
    messagingSenderId: '906140023111',
    projectId: 'jakebrakelogistics-2e451',
    storageBucket: 'jakebrakelogistics-2e451.appspot.com',
    iosClientId: '906140023111-csoll5k55g4qgt8blltlo0slr66tgm71.apps.googleusercontent.com',
    iosBundleId: 'com.example.jb1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrg8kXQG4mmVOi-plWyRy21_izDh7hyWE',
    appId: '1:906140023111:ios:9c943918c139da8d6e7462',
    messagingSenderId: '906140023111',
    projectId: 'jakebrakelogistics-2e451',
    storageBucket: 'jakebrakelogistics-2e451.appspot.com',
    iosClientId: '906140023111-2iohef7bpea7a1tbaiehfd8lb3jrq998.apps.googleusercontent.com',
    iosBundleId: 'com.example.jb1.RunnerTests',
  );
}
